export default {
	AF: { color: '#AEC6CF', name: 'Afganistan', capital: 'Kabul' },
	AX: { color: '#77DD77', name: 'Wyspy Alandzkie', capital: 'Mariehamn' },
	AL: { color: '#77DD77', name: 'Albania', capital: 'Tirana' },
	DZ: { color: '#FFB347', name: 'Algieria', capital: 'Algier' },
	AS: { color: '#FFB7CE', name: 'Samoa Amerykańskie', capital: 'Pago Pago' },
	AD: { color: '#77DD77', name: 'Andora', capital: 'Andora' },
	AO: { color: '#FFB347', name: 'Angola', capital: 'Luanda' },
	AI: { color: '#C3B1E1', name: 'Anguilla', capital: 'The Valley' },
	AQ: { color: '#D3D3D3', name: 'Antarktyda', capital: 'Brak' },
	AG: { color: '#C3B1E1', name: 'Antigua i Barbuda', capital: 'Saint John’s' },
	AR: { color: '#FFD230', name: 'Argentyna', capital: 'Buenos Aires' },
	AM: { color: '#AEC6CF', name: 'Armenia', capital: 'Erywań' },
	AW: { color: '#C3B1E1', name: 'Aruba', capital: 'Oranjestad' },
	AU: { color: '#FFB7CE', name: 'Australia', capital: 'Canberra' },
	AT: { color: '#77DD77', name: 'Austria', capital: 'Wiedeń' },
	AZ: { color: '#AEC6CF', name: 'Azerbejdżan', capital: 'Baku' },
	BS: { color: '#C3B1E1', name: 'Bahamy', capital: 'Nassau' },
	BH: { color: '#AEC6CF', name: 'Bahrajn', capital: 'Manama' },
	BD: { color: '#AEC6CF', name: 'Bangladesz', capital: 'Dhaka' },
	BB: { color: '#C3B1E1', name: 'Barbados', capital: 'Bridgetown' },
	BY: { color: '#77DD77', name: 'Białoruś', capital: 'Mińsk' },
	BE: { color: '#77DD77', name: 'Belgia', capital: 'Bruksela' },
	BZ: { color: '#C3B1E1', name: 'Belize', capital: 'Belmopan' },
	BJ: { color: '#FFB347', name: 'Benin', capital: 'Porto-Novo' },
	BM: { color: '#C3B1E1', name: 'Bermudy', capital: 'Hamilton' },
	BT: { color: '#AEC6CF', name: 'Bhutan', capital: 'Thimphu' },
	BO: { color: '#FFD230', name: 'Boliwia', capital: 'Sucre' },
	BA: { color: '#77DD77', name: 'Bośnia i Hercegowina', capital: 'Sarajewo' },
	BW: { color: '#FFB347', name: 'Botswana', capital: 'Gaborone' },
	BR: { color: '#FFD230', name: 'Brazylia', capital: 'Brasília' },
	IO: {
		color: '#AEC6CF',
		name: 'Brytyjskie Terytorium Oceanu Indyjskiego',
		capital: 'Diego Garcia',
	},
	VG: { color: '#C3B1E1', name: 'Brytyjskie Wyspy Dziewicze', capital: 'Road Town' },
	BN: { color: '#AEC6CF', name: 'Brunei Darussalam', capital: 'Bandar Seri Begawan' },
	BG: { color: '#77DD77', name: 'Bułgaria', capital: 'Sofia' },
	BF: { color: '#FFB347', name: 'Burkina Faso', capital: 'Wagadugu' },
	BI: { color: '#FFB347', name: 'Burundi', capital: 'Gitega' },
	KH: { color: '#AEC6CF', name: 'Kambodża', capital: 'Phnom Penh' },
	CM: { color: '#FFB347', name: 'Kamerun', capital: 'Jaunde' },
	CA: { color: '#C3B1E1', name: 'Kanada', capital: 'Ottawa' },
	CV: { color: '#FFB347', name: 'Republika Zielonego Przylądka', capital: 'Praia' },
	BQ: { color: '#C3B1E1', name: 'Niderlandy Karaibskie', capital: 'Kralendijk' },
	KY: { color: '#C3B1E1', name: 'Kajmany', capital: 'George Town' },
	CF: { color: '#FFB347', name: 'Republika Środkowoafrykańska', capital: 'Bangi' },
	TD: { color: '#FFB347', name: 'Czad', capital: 'Ndżamena' },
	CL: { color: '#FFD230', name: 'Chile', capital: 'Santiago' },
	CN: { color: '#AEC6CF', name: 'Chiny', capital: 'Pekin' },
	CX: { color: '#AEC6CF', name: 'Wyspa Bożego Narodzenia', capital: 'Flying Fish Cove' },
	CC: { color: '#AEC6CF', name: 'Wyspy Kokosowe', capital: 'West Island' },
	CO: { color: '#FFD230', name: 'Kolumbia', capital: 'Bogota' },
	KM: { color: '#FFB347', name: 'Komory', capital: 'Moroni' },
	CG: { color: '#FFB347', name: 'Kongo', capital: 'Brazzaville' },
	CK: { color: '#FFB7CE', name: 'Wyspy Cooka', capital: 'Avarua' },
	CR: { color: '#C3B1E1', name: 'Kostaryka', capital: 'San José' },
	HR: { color: '#77DD77', name: 'Chorwacja', capital: 'Zagrzeb' },
	CU: { color: '#C3B1E1', name: 'Kuba', capital: 'Hawana' },
	CW: { color: '#C3B1E1', name: 'Curaçao', capital: 'Willemstad' },
	CY: { color: '#77DD77', name: 'Cypr', capital: 'Nikozja' },
	CZ: { color: '#77DD77', name: 'Czechy', capital: 'Praga' },
	CD: { color: '#FFB347', name: 'Demokratyczna Republika Konga', capital: 'Kinszasa' },
	DK: { color: '#77DD77', name: 'Dania', capital: 'Kopenhaga' },
	DJ: { color: '#FFB347', name: 'Dżibuti', capital: 'Dżibuti' },
	DM: { color: '#C3B1E1', name: 'Dominika', capital: 'Roseau' },
	DO: { color: '#C3B1E1', name: 'Dominikana', capital: 'Santo Domingo' },
	EC: { color: '#FFD230', name: 'Ekwador', capital: 'Quito' },
	EG: { color: '#FFB347', name: 'Egipt', capital: 'Kair' },
	SV: { color: '#C3B1E1', name: 'Salwador', capital: 'San Salvador' },
	GQ: { color: '#FFB347', name: 'Gwinea Równikowa', capital: 'Malabo' },
	ER: { color: '#FFB347', name: 'Erytrea', capital: 'Asmara' },
	EE: { color: '#77DD77', name: 'Estonia', capital: 'Tallinn' },
	ET: { color: '#FFB347', name: 'Etiopia', capital: 'Addis Abeba' },
	FK: { color: '#FFD230', name: 'Falklandy', capital: 'Stanley' },
	FO: { color: '#77DD77', name: 'Wyspy Owcze', capital: 'Tórshavn' },
	FM: { color: '#FFB7CE', name: 'Mikronezja', capital: 'Palikir' },
	FJ: { color: '#FFB7CE', name: 'Fidżi', capital: 'Suva' },
	FI: { color: '#77DD77', name: 'Finlandia', capital: 'Helsinki' },
	FR: { color: '#77DD77', name: 'Francja', capital: 'Paryż' },
	GF: { color: '#FFD230', name: 'Gujana Francuska', capital: 'Cayenne' },
	PF: { color: '#FFB7CE', name: 'Polinezja Francuska', capital: 'Papeete' },
	TF: {
		color: '#D3D3D3',
		name: 'Francuskie Terytoria Południowe i Antarktyczne',
		capital: 'Brak',
	},
	GA: { color: '#FFB347', name: 'Gabon', capital: 'Libreville' },
	GM: { color: '#FFB347', name: 'Gambia', capital: 'Bandżul' },
	GE: { color: '#AEC6CF', name: 'Gruzja', capital: 'Tbilisi' },
	DE: { color: '#77DD77', name: 'Niemcy', capital: 'Berlin' },
	GH: { color: '#FFB347', name: 'Ghana', capital: 'Akra' },
	GI: { color: '#77DD77', name: 'Gibraltar', capital: 'Gibraltar' },
	GR: { color: '#77DD77', name: 'Grecja', capital: 'Ateny' },
	GL: { color: '#C3B1E1', name: 'Grenlandia', capital: 'Nuuk' },
	GD: { color: '#C3B1E1', name: 'Grenada', capital: 'Saint George’s' },
	GP: { color: '#C3B1E1', name: 'Gwadelupa', capital: 'Basse-Terre' },
	GU: { color: '#FFB7CE', name: 'Guam', capital: 'Hagåtña' },
	GT: { color: '#C3B1E1', name: 'Gwatemala', capital: 'Gwatemala' },
	GN: { color: '#FFB347', name: 'Gwinea', capital: 'Konakry' },
	GW: { color: '#FFB347', name: 'Gwinea Bissau', capital: 'Bissau' },
	GY: { color: '#FFD230', name: 'Gujana', capital: 'Georgetown' },
	HT: { color: '#C3B1E1', name: 'Haiti', capital: 'Port-au-Prince' },
	HN: { color: '#C3B1E1', name: 'Honduras', capital: 'Tegucigalpa' },
	HK: { color: '#AEC6CF', name: 'Hongkong', capital: 'Brak' },
	HU: { color: '#77DD77', name: 'Węgry', capital: 'Budapeszt' },
	IS: { color: '#77DD77', name: 'Islandia', capital: 'Reykjavík' },
	IN: { color: '#AEC6CF', name: 'Indie', capital: 'Nowe Delhi' },
	ID: { color: '#AEC6CF', name: 'Indonezja', capital: 'Dżakarta' },
	IR: { color: '#AEC6CF', name: 'Iran', capital: 'Teheran' },
	IQ: { color: '#AEC6CF', name: 'Irak', capital: 'Bagdad' },
	IE: { color: '#77DD77', name: 'Irlandia', capital: 'Dublin' },
	IM: { color: '#77DD77', name: 'Wyspa Man', capital: 'Douglas' },
	IL: { color: '#AEC6CF', name: 'Izrael', capital: 'Jerozolima' },
	IT: { color: '#77DD77', name: 'Włochy', capital: 'Rzym' },
	CI: { color: '#FFB347', name: 'Wybrzeże Kości Słoniowej', capital: 'Jamusukro' },
	JM: { color: '#C3B1E1', name: 'Jamajka', capital: 'Kingston' },
	JP: { color: '#AEC6CF', name: 'Japonia', capital: 'Tokio' },
	JE: { color: '#77DD77', name: 'Jersey', capital: 'Saint Helier' },
	JO: { color: '#AEC6CF', name: 'Jordania', capital: 'Amman' },
	KZ: { color: '#AEC6CF', name: 'Kazachstan', capital: 'Astana' },
	KE: { color: '#FFB347', name: 'Kenia', capital: 'Nairobi' },
	KI: { color: '#FFB7CE', name: 'Kiribati', capital: 'South Tarawa' },
	XK: { color: '#77DD77', name: 'Kosowo', capital: 'Prisztina' },
	KW: { color: '#AEC6CF', name: 'Kuwejt', capital: 'Kuwejt' },
	KG: { color: '#AEC6CF', name: 'Kirgistan', capital: 'Biszkek' },
	LA: { color: '#AEC6CF', name: 'Laos', capital: 'Wientian' },
	LV: { color: '#77DD77', name: 'Łotwa', capital: 'Ryga' },
	LB: { color: '#AEC6CF', name: 'Liban', capital: 'Bejrut' },
	LS: { color: '#FFB347', name: 'Lesotho', capital: 'Maseru' },
	LR: { color: '#FFB347', name: 'Liberia', capital: 'Monrovia' },
	LY: { color: '#FFB347', name: 'Libia', capital: 'Trypolis' },
	LI: { color: '#77DD77', name: 'Liechtenstein', capital: 'Vaduz' },
	LT: { color: '#77DD77', name: 'Litwa', capital: 'Wilno' },
	LU: { color: '#77DD77', name: 'Luksemburg', capital: 'Luksemburg' },
	MO: { color: '#AEC6CF', name: 'Makau', capital: 'Brak' },
	MK: { color: '#77DD77', name: 'Macedonia Północna', capital: 'Skopje' },
	MG: { color: '#FFB347', name: 'Madagaskar', capital: 'Antananarywa' },
	MW: { color: '#FFB347', name: 'Malawi', capital: 'Lilongwe' },
	MY: { color: '#AEC6CF', name: 'Malezja', capital: 'Kuala Lumpur' },
	MV: { color: '#AEC6CF', name: 'Malediwy', capital: 'Male' },
	ML: { color: '#FFB347', name: 'Mali', capital: 'Bamako' },
	MT: { color: '#77DD77', name: 'Malta', capital: 'Valletta' },
	MH: { color: '#FFB7CE', name: 'Wyspy Marshalla', capital: 'Majuro' },
	MQ: { color: '#C3B1E1', name: 'Martynika', capital: 'Fort-de-France' },
	MR: { color: '#FFB347', name: 'Mauretania', capital: 'Nawakszut' },
	MU: { color: '#FFB347', name: 'Mauritius', capital: 'Port Louis' },
	YT: { color: '#FFB347', name: 'Majotta', capital: 'Mamoudzou' },
	MX: { color: '#C3B1E1', name: 'Meksyk', capital: 'Meksyk' },
	MD: { color: '#77DD77', name: 'Mołdawia', capital: 'Kiszyniów' },
	MC: { color: '#77DD77', name: 'Monako', capital: 'Monako' },
	MN: { color: '#AEC6CF', name: 'Mongolia', capital: 'Ułan Bator' },
	ME: { color: '#77DD77', name: 'Czarnogóra', capital: 'Podgorica' },
	MS: {
		color: '#C3B1E1',
		name: 'Montserrat',
		capital: 'Plymouth (zniszczone) / Brades (de facto)',
	},
	MA: { color: '#FFB347', name: 'Maroko', capital: 'Rabat' },
	MZ: { color: '#FFB347', name: 'Mozambik', capital: 'Maputo' },
	MM: { color: '#AEC6CF', name: 'Birma', capital: 'Naypyidaw' },
	NA: { color: '#FFB347', name: 'Namibia', capital: 'Windhuk' },
	NR: { color: '#FFB7CE', name: 'Nauru', capital: 'Yaren (de facto)' },
	NP: { color: '#AEC6CF', name: 'Nepal', capital: 'Katmandu' },
	NL: { color: '#77DD77', name: 'Holandia', capital: 'Amsterdam' },
	NC: { color: '#FFB7CE', name: 'Nowa Kaledonia', capital: 'Nouméa' },
	NZ: { color: '#FFB7CE', name: 'Nowa Zelandia', capital: 'Wellington' },
	NI: { color: '#C3B1E1', name: 'Nikaragua', capital: 'Managua' },
	NE: { color: '#FFB347', name: 'Niger', capital: 'Niamey' },
	NG: { color: '#FFB347', name: 'Nigeria', capital: 'Abudża' },
	NU: { color: '#FFB7CE', name: 'Niue', capital: 'Alofi' },
	NF: { color: '#FFB7CE', name: 'Wyspa Norfolk', capital: 'Kingston' },
	KP: { color: '#AEC6CF', name: 'Korea Północna', capital: 'Pjongjang' },
	MP: { color: '#FFB7CE', name: 'Mariany Północne', capital: 'Saipan' },
	NO: { color: '#77DD77', name: 'Norwegia', capital: 'Oslo' },
	OM: { color: '#AEC6CF', name: 'Oman', capital: 'Maskat' },
	PK: { color: '#AEC6CF', name: 'Pakistan', capital: 'Islamabad' },
	PW: { color: '#FFB7CE', name: 'Palau', capital: 'Ngerulmud' },
	PS: { color: '#AEC6CF', name: 'Palestyna', capital: 'Ramallah (de facto)' },
	PA: { color: '#C3B1E1', name: 'Panama', capital: 'Panama' },
	PG: { color: '#FFB7CE', name: 'Papua-Nowa Gwinea', capital: 'Port Moresby' },
	PY: { color: '#FFD230', name: 'Paragwaj', capital: 'Asuncion' },
	PE: { color: '#FFD230', name: 'Peru', capital: 'Lima' },
	PH: { color: '#AEC6CF', name: 'Filipiny', capital: 'Manila' },
	PN: { color: '#FFB7CE', name: 'Wyspy Pitcairn', capital: 'Adamstown' },
	PL: { color: '#77DD77', name: 'Polska', capital: 'Warszawa' },
	PT: { color: '#77DD77', name: 'Portugalia', capital: 'Lizbona' },
	PR: { color: '#C3B1E1', name: 'Puerto Rico', capital: 'San Juan' },
	QA: { color: '#AEC6CF', name: 'Katar', capital: 'Doha' },
	RE: { color: '#FFB347', name: 'Reunion', capital: 'Saint-Denis' },
	RO: { color: '#77DD77', name: 'Rumunia', capital: 'Bukareszt' },
	RU: { color: '#77DD77', name: 'Rosja', capital: 'Moskwa' },
	RW: { color: '#FFB347', name: 'Rwanda', capital: 'Kigali' },
	SH: { color: '#FFB347', name: 'Wyspa Świętej Heleny', capital: 'Jamestown' },
	KN: { color: '#C3B1E1', name: 'Saint Kitts i Nevis', capital: 'Basseterre' },
	LC: { color: '#C3B1E1', name: 'Saint Lucia', capital: 'Castries' },
	PM: { color: '#C3B1E1', name: 'Saint-Pierre i Miquelon', capital: 'Saint-Pierre' },
	VC: { color: '#C3B1E1', name: 'Saint Vincent i Grenadyny', capital: 'Kingstown' },
	WS: { color: '#FFB7CE', name: 'Samoa', capital: 'Apia' },
	SM: { color: '#77DD77', name: 'San Marino', capital: 'San Marino' },
	ST: { color: '#FFB347', name: 'São Tomé i Príncipe', capital: 'São Tomé' },
	SA: { color: '#AEC6CF', name: 'Arabia Saudyjska', capital: 'Rijad' },
	SN: { color: '#FFB347', name: 'Senegal', capital: 'Dakar' },
	RS: { color: '#77DD77', name: 'Serbia', capital: 'Belgrad' },
	SC: { color: '#FFB347', name: 'Seszele', capital: 'Victoria' },
	SL: { color: '#FFB347', name: 'Sierra Leone', capital: 'Freetown' },
	SG: { color: '#AEC6CF', name: 'Singapur', capital: 'Singapur' },
	SX: { color: '#C3B1E1', name: 'Sint Maarten', capital: 'Philipsburg' },
	SK: { color: '#77DD77', name: 'Słowacja', capital: 'Bratysława' },
	SI: { color: '#77DD77', name: 'Słowenia', capital: 'Lublana' },
	SB: { color: '#FFB7CE', name: 'Wyspy Salomona', capital: 'Honiara' },
	SO: { color: '#FFB347', name: 'Somalia', capital: 'Mogadiszu' },
	ZA: {
		color: '#FFB347',
		name: 'Południowa Afryka',
		capital: 'Pretoria (faktycznie rządowa)',
	},
	GS: {
		color: '#D3D3D3',
		name: 'Georgia Południowa i Wyspy Sandwich Południowe',
		capital: 'King Edward Point',
	},
	KR: { color: '#AEC6CF', name: 'Korea Południowa', capital: 'Seul' },
	SS: { color: '#FFB347', name: 'Sudan Południowy', capital: 'Dżuba' },
	ES: { color: '#77DD77', name: 'Hiszpania', capital: 'Madryt' },
	LK: { color: '#AEC6CF', name: 'Sri Lanka', capital: 'Sri Dźajawardanapura Kotte' },
	SD: { color: '#FFB347', name: 'Sudan', capital: 'Chartum' },
	SR: { color: '#FFD230', name: 'Surinam', capital: 'Paramaribo' },
	SJ: { color: '#77DD77', name: 'Svalbard i Jan Mayen', capital: 'Longyearbyen (Svalbard)' },
	SZ: { color: '#FFB347', name: 'Eswatini', capital: 'Mbabane (administracyjna)' },
	SE: { color: '#77DD77', name: 'Szwecja', capital: 'Sztokholm' },
	CH: { color: '#77DD77', name: 'Szwajcaria', capital: 'Berno' },
	SY: { color: '#AEC6CF', name: 'Syria', capital: 'Damaszek' },
	TW: { color: '#AEC6CF', name: 'Tajwan', capital: 'Tajpej' },
	TJ: { color: '#AEC6CF', name: 'Tadżykistan', capital: 'Duszanbe' },
	TZ: { color: '#FFB347', name: 'Tanzania', capital: 'Dodoma' },
	TH: { color: '#AEC6CF', name: 'Tajlandia', capital: 'Bangkok' },
	TL: { color: '#AEC6CF', name: 'Timor Wschodni', capital: 'Dili' },
	TG: { color: '#FFB347', name: 'Togo', capital: 'Lomé' },
	TK: { color: '#FFB7CE', name: 'Tokelau', capital: 'Brak' },
	TO: { color: '#FFB7CE', name: 'Tonga', capital: 'Nukuʻalofa' },
	TT: { color: '#C3B1E1', name: 'Trynidad i Tobago', capital: 'Port-of-Spain' },
	TN: { color: '#FFB347', name: 'Tunezja', capital: 'Tunis' },
	TR: { color: '#AEC6CF', name: 'Turcja', capital: 'Ankara' },
	TM: { color: '#AEC6CF', name: 'Turkmenistan', capital: 'Aszchabad' },
	TC: { color: '#C3B1E1', name: 'Wyspy Turks i Caicos', capital: 'Cockburn Town' },
	TV: { color: '#FFB7CE', name: 'Tuvalu', capital: 'Funafuti' },
	UG: { color: '#FFB347', name: 'Uganda', capital: 'Kampala' },
	UA: { color: '#77DD77', name: 'Ukraina', capital: 'Kijów' },
	AE: { color: '#AEC6CF', name: 'Zjednoczone Emiraty Arabskie', capital: 'Abu Zabi' },
	GB: { color: '#77DD77', name: 'Wielka Brytania', capital: 'Londyn' },
	US: { color: '#C3B1E1', name: 'Stany Zjednoczone', capital: 'Waszyngton' },
	UM: {
		color: '#FFB7CE',
		name: 'Małe Wyspy Oddalone Stanów Zjednoczonych',
		capital: 'Brak',
	},
	VI: {
		color: '#C3B1E1',
		name: 'Wyspy Dziewicze Stanów Zjednoczonych',
		capital: 'Charlotte Amalie',
	},
	UY: { color: '#FFD230', name: 'Urugwaj', capital: 'Montevideo' },
	UZ: { color: '#AEC6CF', name: 'Uzbekistan', capital: 'Taszkent' },
	VU: { color: '#FFB7CE', name: 'Vanuatu', capital: 'Port Vila' },
	VA: { color: '#77DD77', name: 'Watykan', capital: 'Watykan' },
	VE: { color: '#FFD230', name: 'Wenezuela', capital: 'Caracas' },
	VN: { color: '#AEC6CF', name: 'Wietnam', capital: 'Hanoi' },
	WF: { color: '#FFB7CE', name: 'Wallis i Futuna', capital: 'Mata Utu' },
	EH: { color: '#FFB347', name: 'Sahara Zachodnia', capital: 'Al-Ujun' },
	YE: { color: '#AEC6CF', name: 'Jemen', capital: 'Sana' },
	ZM: { color: '#FFB347', name: 'Zambia', capital: 'Lusaka' },
	ZW: { color: '#FFB347', name: 'Zimbabwe', capital: 'Harare' },
};
