export default {
	AF: { capital: 'Kabul', continent: 'Azja' },
	AX: { capital: 'Mariehamn', continent: 'Europa' },
	AL: { capital: 'Tirana', continent: 'Europa' },
	DZ: { capital: 'Algier', continent: 'Afryka' },
	AS: { capital: 'Pago Pago', continent: 'Australia i Oceania' },
	AD: { capital: 'Andora', continent: 'Europa' },
	AO: { capital: 'Luanda', continent: 'Afryka' },
	AI: { capital: 'The Valley', continent: 'Ameryka Północna' },
	AQ: { capital: 'Brak', continent: 'Antarktyda' },
	AG: { capital: 'Saint John’s', continent: 'Ameryka Północna' },
	AR: { capital: 'Buenos Aires', continent: 'Ameryka Południowa' },
	AM: { capital: 'Erywań', continent: 'Azja' },
	AW: { capital: 'Oranjestad', continent: 'Ameryka Północna' },
	AU: { capital: 'Canberra', continent: 'Australia i Oceania' },
	AT: { capital: 'Wiedeń', continent: 'Europa' },
	AZ: { capital: 'Baku', continent: 'Azja' },
	BS: { capital: 'Nassau', continent: 'Ameryka Północna' },
	BH: { capital: 'Manama', continent: 'Azja' },
	BD: { capital: 'Dhaka', continent: 'Azja' },
	BB: { capital: 'Bridgetown', continent: 'Ameryka Północna' },
	BY: { capital: 'Mińsk', continent: 'Europa' },
	BE: { capital: 'Bruksela', continent: 'Europa' },
	BZ: { capital: 'Belmopan', continent: 'Ameryka Północna' },
	BJ: { capital: 'Porto-Novo', continent: 'Afryka' },
	BM: { capital: 'Hamilton', continent: 'Ameryka Północna' },
	BT: { capital: 'Thimphu', continent: 'Azja' },
	BO: { capital: 'Sucre', continent: 'Ameryka Południowa' },
	BA: { capital: 'Sarajewo', continent: 'Europa' },
	BW: { capital: 'Gaborone', continent: 'Afryka' },
	BR: { capital: 'Brasília', continent: 'Ameryka Południowa' },
	IO: { capital: 'Diego Garcia', continent: 'Azja' },
	VG: { capital: 'Road Town', continent: 'Ameryka Północna' },
	BN: { capital: 'Bandar Seri Begawan', continent: 'Azja' },
	BG: { capital: 'Sofia', continent: 'Europa' },
	BF: { capital: 'Wagadugu', continent: 'Afryka' },
	BI: { capital: 'Gitega', continent: 'Afryka' },
	KH: { capital: 'Phnom Penh', continent: 'Azja' },
	CM: { capital: 'Jaunde', continent: 'Afryka' },
	CA: { capital: 'Ottawa', continent: 'Ameryka Północna' },
	CV: { capital: 'Praia', continent: 'Afryka' },
	BQ: { capital: 'Kralendijk', continent: 'Ameryka Północna' },
	KY: { capital: 'George Town', continent: 'Ameryka Północna' },
	CF: { capital: 'Bangi', continent: 'Afryka' },
	TD: { capital: 'Ndżamena', continent: 'Afryka' },
	CL: { capital: 'Santiago', continent: 'Ameryka Południowa' },
	CN: { capital: 'Pekin', continent: 'Azja' },
	CX: { capital: 'Flying Fish Cove', continent: 'Azja' },
	CC: { capital: 'West Island', continent: 'Azja' },
	CO: { capital: 'Bogota', continent: 'Ameryka Południowa' },
	KM: { capital: 'Moroni', continent: 'Afryka' },
	CG: { capital: 'Brazzaville', continent: 'Afryka' },
	CK: { capital: 'Avarua', continent: 'Australia i Oceania' },
	CR: { capital: 'San José', continent: 'Ameryka Północna' },
	HR: { capital: 'Zagrzeb', continent: 'Europa' },
	CU: { capital: 'Hawana', continent: 'Ameryka Północna' },
	CW: { capital: 'Willemstad', continent: 'Ameryka Północna' },
	CY: { capital: 'Nikozja', continent: 'Europa' },
	CZ: { capital: 'Praga', continent: 'Europa' },
	CD: { capital: 'Kinszasa', continent: 'Afryka' },
	DK: { capital: 'Kopenhaga', continent: 'Europa' },
	DJ: { capital: 'Dżibuti', continent: 'Afryka' },
	DM: { capital: 'Roseau', continent: 'Ameryka Północna' },
	DO: { capital: 'Santo Domingo', continent: 'Ameryka Północna' },
	EC: { capital: 'Quito', continent: 'Ameryka Południowa' },
	EG: { capital: 'Kair', continent: 'Afryka' },
	SV: { capital: 'San Salvador', continent: 'Ameryka Północna' },
	GQ: { capital: 'Malabo', continent: 'Afryka' },
	ER: { capital: 'Asmara', continent: 'Afryka' },
	EE: { capital: 'Tallinn', continent: 'Europa' },
	ET: { capital: 'Addis Abeba', continent: 'Afryka' },
	FK: { capital: 'Stanley', continent: 'Ameryka Południowa' },
	FO: { capital: 'Tórshavn', continent: 'Europa' },
	FM: { capital: 'Palikir', continent: 'Australia i Oceania' },
	FJ: { capital: 'Suva', continent: 'Australia i Oceania' },
	FI: { capital: 'Helsinki', continent: 'Europa' },
	FR: { capital: 'Paryż', continent: 'Europa' },
	GF: { capital: 'Cayenne', continent: 'Ameryka Południowa' },
	PF: { capital: 'Papeete', continent: 'Australia i Oceania' },
	TF: { capital: 'Brak', continent: 'Antarktyda' },
	GA: { capital: 'Libreville', continent: 'Afryka' },
	GM: { capital: 'Bandżul', continent: 'Afryka' },
	GE: { capital: 'Tbilisi', continent: 'Azja' },
	DE: { capital: 'Berlin', continent: 'Europa' },
	GH: { capital: 'Akra', continent: 'Afryka' },
	GI: { capital: 'Gibraltar', continent: 'Europa' },
	GR: { capital: 'Ateny', continent: 'Europa' },
	GL: { capital: 'Nuuk', continent: 'Ameryka Północna' },
	GD: { capital: 'Saint George’s', continent: 'Ameryka Północna' },
	GP: { capital: 'Basse-Terre', continent: 'Ameryka Północna' },
	GU: { capital: 'Hagåtña', continent: 'Australia i Oceania' },
	GT: { capital: 'Gwatemala', continent: 'Ameryka Północna' },
	GN: { capital: 'Konakry', continent: 'Afryka' },
	GW: { capital: 'Bissau', continent: 'Afryka' },
	GY: { capital: 'Georgetown', continent: 'Ameryka Południowa' },
	HT: { capital: 'Port-au-Prince', continent: 'Ameryka Północna' },
	HN: { capital: 'Tegucigalpa', continent: 'Ameryka Północna' },
	HK: { capital: 'Brak', continent: 'Azja' },
	HU: { capital: 'Budapeszt', continent: 'Europa' },
	IS: { capital: 'Reykjavík', continent: 'Europa' },
	IN: { capital: 'Nowe Delhi', continent: 'Azja' },
	ID: { capital: 'Dżakarta', continent: 'Azja' },
	IR: { capital: 'Teheran', continent: 'Azja' },
	IQ: { capital: 'Bagdad', continent: 'Azja' },
	IE: { capital: 'Dublin', continent: 'Europa' },
	IM: { capital: 'Douglas', continent: 'Europa' },
	IL: { capital: 'Jerozolima', continent: 'Azja' },
	IT: { capital: 'Rzym', continent: 'Europa' },
	CI: { capital: 'Jamusukro', continent: 'Afryka' },
	JM: { capital: 'Kingston', continent: 'Ameryka Północna' },
	JP: { capital: 'Tokio', continent: 'Azja' },
	JE: { capital: 'Saint Helier', continent: 'Europa' },
	JO: { capital: 'Amman', continent: 'Azja' },
	KZ: { capital: 'Astana', continent: 'Azja' },
	KE: { capital: 'Nairobi', continent: 'Afryka' },
	KI: { capital: 'South Tarawa', continent: 'Australia i Oceania' },
	XK: { capital: 'Prisztina', continent: 'Europa' },
	KW: { capital: 'Kuwejt', continent: 'Azja' },
	KG: { capital: 'Biszkek', continent: 'Azja' },
	LA: { capital: 'Wientian', continent: 'Azja' },
	LV: { capital: 'Ryga', continent: 'Europa' },
	LB: { capital: 'Bejrut', continent: 'Azja' },
	LS: { capital: 'Maseru', continent: 'Afryka' },
	LR: { capital: 'Monrovia', continent: 'Afryka' },
	LY: { capital: 'Trypolis', continent: 'Afryka' },
	LI: { capital: 'Vaduz', continent: 'Europa' },
	LT: { capital: 'Wilno', continent: 'Europa' },
	LU: { capital: 'Luksemburg', continent: 'Europa' },
	MO: { capital: 'Brak', continent: 'Azja' },
	MK: { capital: 'Skopje', continent: 'Europa' },
	MG: { capital: 'Antananarywa', continent: 'Afryka' },
	MW: { capital: 'Lilongwe', continent: 'Afryka' },
	MY: { capital: 'Kuala Lumpur', continent: 'Azja' },
	MV: { capital: 'Male', continent: 'Azja' },
	ML: { capital: 'Bamako', continent: 'Afryka' },
	MT: { capital: 'Valletta', continent: 'Europa' },
	MH: { capital: 'Majuro', continent: 'Australia i Oceania' },
	MQ: { capital: 'Fort-de-France', continent: 'Ameryka Północna' },
	MR: { capital: 'Nawakszut', continent: 'Afryka' },
	MU: { capital: 'Port Louis', continent: 'Afryka' },
	YT: { capital: 'Mamoudzou', continent: 'Afryka' },
	MX: { capital: 'Meksyk', continent: 'Ameryka Północna' },
	MD: { capital: 'Kiszyniów', continent: 'Europa' },
	MC: { capital: 'Monako', continent: 'Europa' },
	MN: { capital: 'Ułan Bator', continent: 'Azja' },
	ME: { capital: 'Podgorica', continent: 'Europa' },
	MS: {
		capital: 'Plymouth (zniszczone) / Brades (de facto)',
		continent: 'Ameryka Północna',
	},
	MA: { capital: 'Rabat', continent: 'Afryka' },
	MZ: { capital: 'Maputo', continent: 'Afryka' },
	MM: { capital: 'Naypyidaw', continent: 'Azja' },
	NA: { capital: 'Windhuk', continent: 'Afryka' },
	NR: { capital: 'Yaren (de facto)', continent: 'Australia i Oceania' },
	NP: { capital: 'Katmandu', continent: 'Azja' },
	NL: { capital: 'Amsterdam', continent: 'Europa' },
	NC: { capital: 'Nouméa', continent: 'Australia i Oceania' },
	NZ: { capital: 'Wellington', continent: 'Australia i Oceania' },
	NI: { capital: 'Managua', continent: 'Ameryka Północna' },
	NE: { capital: 'Niamey', continent: 'Afryka' },
	NG: { capital: 'Abudża', continent: 'Afryka' },
	NU: { capital: 'Alofi', continent: 'Australia i Oceania' },
	NF: { capital: 'Kingston', continent: 'Australia i Oceania' },
	KP: { capital: 'Pjongjang', continent: 'Azja' },
	MP: { capital: 'Saipan', continent: 'Australia i Oceania' },
	NO: { capital: 'Oslo', continent: 'Europa' },
	OM: { capital: 'Maskat', continent: 'Azja' },
	PK: { capital: 'Islamabad', continent: 'Azja' },
	PW: { capital: 'Ngerulmud', continent: 'Australia i Oceania' },
	PS: { capital: 'Ramallah (de facto)', continent: 'Azja' },
	PA: { capital: 'Panama', continent: 'Ameryka Północna' },
	PG: { capital: 'Port Moresby', continent: 'Australia i Oceania' },
	PY: { capital: 'Asuncion', continent: 'Ameryka Południowa' },
	PE: { capital: 'Lima', continent: 'Ameryka Południowa' },
	PH: { capital: 'Manila', continent: 'Azja' },
	PN: { capital: 'Adamstown', continent: 'Australia i Oceania' },
	PL: { capital: 'Warszawa', continent: 'Europa' },
	PT: { capital: 'Lizbona', continent: 'Europa' },
	PR: { capital: 'San Juan', continent: 'Ameryka Północna' },
	QA: { capital: 'Doha', continent: 'Azja' },
	RE: { capital: 'Saint-Denis', continent: 'Afryka' },
	RO: { capital: 'Bukareszt', continent: 'Europa' },
	RU: { capital: 'Moskwa', continent: 'Europa' },
	RW: { capital: 'Kigali', continent: 'Afryka' },
	SH: { capital: 'Jamestown', continent: 'Afryka' },
	KN: { capital: 'Basseterre', continent: 'Ameryka Północna' },
	LC: { capital: 'Castries', continent: 'Ameryka Północna' },
	PM: { capital: 'Saint-Pierre', continent: 'Ameryka Północna' },
	VC: { capital: 'Kingstown', continent: 'Ameryka Północna' },
	WS: { capital: 'Apia', continent: 'Australia i Oceania' },
	SM: { capital: 'San Marino', continent: 'Europa' },
	ST: { capital: 'São Tomé', continent: 'Afryka' },
	SA: { capital: 'Rijad', continent: 'Azja' },
	SN: { capital: 'Dakar', continent: 'Afryka' },
	RS: { capital: 'Belgrad', continent: 'Europa' },
	SC: { capital: 'Victoria', continent: 'Afryka' },
	SL: { capital: 'Freetown', continent: 'Afryka' },
	SG: { capital: 'Singapur', continent: 'Azja' },
	SX: { capital: 'Philipsburg', continent: 'Ameryka Północna' },
	SK: { capital: 'Bratysława', continent: 'Europa' },
	SI: { capital: 'Lublana', continent: 'Europa' },
	SB: { capital: 'Honiara', continent: 'Australia i Oceania' },
	SO: { capital: 'Mogadiszu', continent: 'Afryka' },
	ZA: {
		capital: 'Pretoria (faktycznie rządowa)',
		continent: 'Afryka',
	},
	GS: { capital: 'King Edward Point', continent: 'Antarktyda' },
	KR: { capital: 'Seul', continent: 'Azja' },
	SS: { capital: 'Dżuba', continent: 'Afryka' },
	ES: { capital: 'Madryt', continent: 'Europa' },
	LK: {
		capital: 'Sri Dźajawardanapura Kotte',
		continent: 'Azja',
	},
	SD: { capital: 'Chartum', continent: 'Afryka' },
	SR: { capital: 'Paramaribo', continent: 'Ameryka Południowa' },
	SJ: { capital: 'Longyearbyen (Svalbard)', continent: 'Europa' },
	SZ: { capital: 'Mbabane (administracyjna)', continent: 'Afryka' },
	SE: { capital: 'Sztokholm', continent: 'Europa' },
	CH: { capital: 'Berno', continent: 'Europa' },
	SY: { capital: 'Damaszek', continent: 'Azja' },
	TW: { capital: 'Tajpej', continent: 'Azja' },
	TJ: { capital: 'Duszanbe', continent: 'Azja' },
	TZ: { capital: 'Dodoma', continent: 'Afryka' },
	TH: { capital: 'Bangkok', continent: 'Azja' },
	TL: { capital: 'Dili', continent: 'Azja' },
	TG: { capital: 'Lomé', continent: 'Afryka' },
	TK: { capital: 'Brak', continent: 'Australia i Oceania' },
	TO: { capital: 'Nukuʻalofa', continent: 'Australia i Oceania' },
	TT: { capital: 'Port-of-Spain', continent: 'Ameryka Północna' },
	TN: { capital: 'Tunis', continent: 'Afryka' },
	TR: { capital: 'Ankara', continent: 'Azja' },
	TM: { capital: 'Aszchabad', continent: 'Azja' },
	TC: { capital: 'Cockburn Town', continent: 'Ameryka Północna' },
	TV: { capital: 'Funafuti', continent: 'Australia i Oceania' },
	UG: { capital: 'Kampala', continent: 'Afryka' },
	UA: { capital: 'Kijów', continent: 'Europa' },
	AE: { capital: 'Abu Zabi', continent: 'Azja' },
	GB: { capital: 'Londyn', continent: 'Europa' },
	US: { capital: 'Waszyngton', continent: 'Ameryka Północna' },
	UM: { capital: 'Brak', continent: 'Australia i Oceania' },
	VI: { capital: 'Charlotte Amalie', continent: 'Ameryka Północna' },
	UY: { capital: 'Montevideo', continent: 'Ameryka Południowa' },
	UZ: { capital: 'Taszkent', continent: 'Azja' },
	VU: { capital: 'Port Vila', continent: 'Australia i Oceania' },
	VA: { capital: 'Watykan', continent: 'Europa' },
	VE: { capital: 'Caracas', continent: 'Ameryka Południowa' },
	VN: { capital: 'Hanoi', continent: 'Azja' },
	WF: { capital: 'Mata Utu', continent: 'Australia i Oceania' },
	EH: { capital: 'Al-Ujun', continent: 'Afryka' },
	YE: { capital: 'Sana', continent: 'Azja' },
	ZM: { capital: 'Lusaka', continent: 'Afryka' },
	ZW: { capital: 'Harare', continent: 'Afryka' },
};
